### PR TITLE
Updates to v3

### PR DESCRIPTION
**Pull request by rudle**
Hi @jmaddi, want to make sure you saw this fork. It updates this gem to use the v3 API and (at least to me) makes things work :)

If you could merge this and push a new gem, I'd be very grateful.

Happy Holidays! :santa: :candy: :pineapple:

### CODE REVIEW

**Comment by rudle** [comment]
Oof, looks like things are not quite happy :(

My hopes of integrating with lift.do's API are thwarted :c

**Comment by jmaddi** [comment]
@rudle Thanks for the PR, I have released a new gem for the current API. Let me know if you have any issues.

**Comment by rudle** [comment]
It's working for me! Thanks for the quick resolution.

**Comment by joshroman** [comment]
Very cool, thanks @jmaddi !

**Pull request closed without merging**
